function gui_menu_execution(parameter_evaporation, parameters_MC, parameters_datasets_SSS,...
    parameters_datasets_SST,...
    parameters_computation, parameters_year, parameters_ocean, parameter_precipitation,...
    parameters_season, parameter_heatfluxls, parameter_radfluxls)
% gui_menu_execution                             executes chosen function
%                                                                   with chosen parameters
%============================================================
% 
% USAGE:  
% gui_menu_execution()
%                                                   *called from
%                                                   Control_center.m
%                                                   without input arguments
%
% DESCRIPTION:
%  **As of 04/11/2019 
% Function executes chosen function with user selected variables,
% parameters and datasets
%
% INPUT:
% parameter_evaporation = to hold evaporation dataset choice        [ vector ]
% parameters_MC = to hold number of MC simulations choosen          [ vector ]
% [parameters_datasets_SSS, parameters_datasets_SST] = to hold SSS and SST
%                                                                                                   datasets choice name    [ vector ]  
% parameters_computation = to hold the function to be run       [ vector ]
% parameters_year = to hold the year chosen for the computation to be run       [ array ]
% parameters_ocean = to hold the basin name over which the computation will
%                                                                                           be run          [ vector ]
% parameter_precipitation = to hold the name of the precipitation dataset
%                                                                   chosen           [ vector ]
% parameters_season = to hold the season over which the computation will be run       [ array ]
% parameter_heatfluxls = to hold the name of the heat flux (turbulant comp.) product chosen    
%                                                                                                                 [ vector ]
% parameter_radfluxls = to hold the name of the heat flux product (radiative comp.) product chosen.
%                                                                                                     [ vector ]
% 
% OUTPUT:
% None
% 
% AUTHOR: 
%  Aqeel Piracha            [ apiracha@btinternet.com ]
%
% VERSION NUMBER: 1.1 (Monday 4th November 2019) *******STARTING FRESH COUNT
% NOTES on VERSION:
%
% REFERENCES:
% None
% 
% The software is currently in development
%
%============================================================
      if strcmp(parameters_computation,'wm_denseflux_spatial_NEW')
           wm_denseflux_spatial_NEW(str2double(parameters_MC),...
               parameters_datasets_SSS,...
               parameters_datasets_SST,...
               parameters_year,...
               parameters_ocean,...
               parameter_precipitation,...
               parameters_season,...
               parameter_evaporation,...
               parameter_heatfluxls,...
               parameter_radfluxls)
       elseif strcmp(parameters_computation,'wm_transf_TS_error')
           wm_transf_TS_error(str2double(parameters_MC),...
               parameters_datasets_SSS,...
               parameters_datasets_SST,...
               parameters_year,...
               parameters_ocean,...
               parameter_precipitation,...
               parameters_season,...
               parameter_evaporation,...
               parameter_heatfluxls,...
               parameter_radfluxls)
       elseif strcmp(parameters_computation,'wm_transf_rho_error')
           wm_transf_rho_error(str2double(parameters_MC),...
               parameters_datasets_SSS,...
               parameters_datasets_SST,...
               parameters_year,...
               parameters_ocean,...
               parameter_precipitation,...
               parameters_season,...
               parameter_evaporation,...
               parameter_heatfluxls,...
               parameter_radfluxls)
       elseif strcmp(parameters_computation,'wm_form_TS_error')
           wm_form_TS_error(str2double(parameters_MC),...
               parameters_datasets_SSS,...
               parameters_datasets_SST,...
               parameters_year,...
               parameters_ocean,...
               parameter_precipitation,...
               parameters_season,...
               parameter_evaporation,...
               parameter_heatfluxls,...
               parameter_radfluxls)
       elseif strcmp(parameters_computation,'wm_form_rho_error')
           wm_form_rho_error(str2double(parameters_MC),...
               parameters_datasets_SSS,...
               parameters_datasets_SST,...
               parameters_year,...
               parameters_ocean,...
               parameter_precipitation,...
               parameters_season,...
               parameter_evaporation,...
               parameter_heatfluxls,...
               parameter_radfluxls)       
       elseif strcmp(parameters_computation,'frontiers_paper_figures')
           frontiers_paper_figures(str2double(parameters_MC),...
               parameters_datasets_SSS,...
               parameters_datasets_SST,...
               parameters_year,...
               parameters_ocean,...
               parameter_precipitation,...
               parameters_season,...
               parameter_evaporation,...
               parameter_heatfluxls,...
               parameter_radfluxls)
       end
end