function Monte_carlo_analysis_variables(vare,ocean,var,latitude,longitude,lat,lon,...
    month,tframe,n_stat,~,randnumgen,seed,SSS_unc,SST_unc,H_unc,W_unc,fign,units,unc,name_unit,...
    name,cmin,cmax,width,point_width)
%% SSS
vare_mc_mean = nanmean(vare,4);
vare_mc_std = nanstd(vare,4);
vare_mc_skewness = skewness(vare,0,4);
vare_diff_H_mean = var(:,:,month) - vare_mc_mean(:,:);

% Mean
figure(fign)
clf
set(gcf,'Color','w')
map_basin(latitude,longitude,ocean,lat,lon,vare_mc_mean')
set(gcf,'Colormap',jet)
c = colorbar('Location','eastoutside','FontSize',18);
set(get(c,'ylabel'),'string',...
                name_unit,'fontsize',18)
title({['month = ',num2str(month),' year = 20',[tframe(end-1),tframe(end)]],...
    ['Mean of ',num2str(n_stat),' simulations'],...
    ['Uncertainties: SSS = ',num2str(SSS_unc),'[PSU] - ',...
    'SST = ',num2str(SST_unc),'[\circC] - ',...
    'H = ',num2str(H_unc),'[WM^{-2}] - ',...
    'W = ',num2str(W_unc),'[ms^{-1}]']})
caxis([cmin cmax])

%standard deviation
figure(fign+1)
clf
set(gcf,'Color','w')
map_basin(latitude,longitude,ocean,lat,lon,vare_mc_std')
set(gcf,'Colormap',jet)
c = colorbar('Location','eastoutside','FontSize',18);
set(get(c,'ylabel'),'string',...
                name_unit,'fontsize',18)
title({['month = ',num2str(month),' year = 20',[tframe(end-1),tframe(end)]],...
    ['STD of ',num2str(n_stat),' simulations'],...
    ['Uncertainties: SSS = ',num2str(SSS_unc),'[PSU] - ',...
    'SST = ',num2str(SST_unc),'[\circC] - ',...
    'H = ',num2str(H_unc),'[WM^{-2}] - ',...
    'W = ',num2str(W_unc),'[ms^{-1}]']})
caxis([0 SSS_unc+SSS_unc])

%skewness
figure(fign+2)
clf
set(gcf,'Color','w')
map_basin(latitude,longitude,ocean,lat,lon,vare_mc_skewness')
set(gcf,'Colormap',jet)
c = colorbar('Location','eastoutside','FontSize',18);
set(get(c,'ylabel'),'string',...
                'Skewness','fontsize',18)
title({['month = ',num2str(month),' year = 20',[tframe(end-1),tframe(end)]],...
    ['Skewness of ',num2str(n_stat),' simulations'],...
    ['Uncertainties: SSS = ',num2str(SSS_unc),'[PSU] - ',...
    'SST = ',num2str(SST_unc),'[\circC] - ',...
    'H = ',num2str(H_unc),'[WM^{-2}] - ',...
    'W = ',num2str(W_unc),'[ms^{-1}]']})
caxis([-1 1])

%difference from mean
figure(fign+3)
clf
set(gcf,'Color','w')
map_basin(latitude,longitude,ocean,lat,lon,vare_diff_H_mean')
set(gcf,'Colormap',jet)
c = colorbar('Location','eastoutside','FontSize',18);
set(get(c,'ylabel'),'string',...
                name_unit,'fontsize',18)
title({['month = ',num2str(month),' year = 20',[tframe(end-1),tframe(end)]],...
    ['\DeltaReference-Mean of ',num2str(n_stat),' simulations'],...
    ['Uncertainties: SSS = ',num2str(SSS_unc),'[PSU] - ',...
    'SST = ',num2str(SST_unc),'[\circC] - ',...
    'H = ',num2str(H_unc),'[WM^{-2}] - ',...
    'W = ',num2str(W_unc),'[ms^{-1}]']})
caxis([-(unc) unc])


monte_carlo_hist(var,name,vare,0.2,lat,lon,month,20,30,ocean,fign+4,units,...
    randnumgen,seed,n_stat,unc,fign,vare_diff_H_mean,width,point_width,[],[])
end

