function plotting_all_variables(Frho_true,Frho_mean,Frho_std,...
                gFrho_true,gFrho_mean,gFrho_std,...
                    Fscatt_true,Fscatt_mean,Fscatt_std,...
                        gFscatt_true,gFscatt_mean,gFscatt_std)
%Rho Areas
        new_rho_areas(rho_e,sigma,tframe,month,n_stat,month,SSS,SST,SSS_unc,SST_unc,H_unc,...
                W_unc,dxx,dyy,lon,lat,latitude,longitude,ocean)

        geo_plot(latitude,longitude,lat,lon,permute(Fmean_e,[2,3,1]),SSS_unc,SST_unc,...
            H_unc,W_unc,tframe,ocean,n_stat,month,'Density flux [kgm^{-2}s^{-1}]',24,...
            '[kgm^{-2}s^{-1}]','Fmean',...
            'Density flux',[-1e-5 2e-5],[0 6e-8],0,[],[],[])
%% Plotting Transformation TS
% TS
        TS_plot(permute(Fscatt_error,[2,3,1]),T,S,SSS_unc,SST_unc,H_unc,W_unc,...
            'Transformation [Sv]','[Sv]',30,month,tframe,n_stat,[-1 20],[0 10],'Fscatt_error_t',...
            'Transformation')
% GEO
        TS_geo(permute(Fscatt_error,[2,3,1]),S,T,dS,dT,SSS,SST,n_stat,ocean,longitude,latitude,lat,lon,...
            tframe,SSS_unc,SST_unc,H_unc,W_unc,'[Sv]','Transformation [Sv]',dxx,dyy,36,...
            'Fpeak_t_ts','Transformation',[0 1.5e-9],[0 7e-10],1,month,2,30,SSS,SST,rho_e)
%% Plotting Transformation rho
% RHO
        rho_plot(Frho_all,sigma-1000,tframe,month,n_stat,42,SSS_unc,SST_unc,...
            H_unc,W_unc,'Frho_all','Transformation','[Sv]','Transformation [Sv]')
% GEO
        rho_geo(Frho_all,sigma-1000,ocean,tframe,month,n_stat,48,SSS_unc,SST_unc,...
            H_unc,W_unc,dS,rho,latitude,longitude,lat,lon,dxx,dyy,'Fpeak_t_r',...
            'Transformation','[Sv]','Transformation [Sv]',1,SSS,SST,rho_e)
%% Plotting Formation TS
% TS
        TS_plot(permute(formation_error,[2,3,1]),T,S,SSS_unc,SST_unc,H_unc,W_unc,...
            'Formation [Sv]','[Sv]',54,month,tframe,n_stat,[-2 2],[0 1],'formation_error','Formation')
% GEO
        TS_geo(permute(formation_error,[2,3,1]),S,T,dS,dT,SSS,SST,n_stat,ocean,...
            longitude,latitude,lat,lon,tframe,SSS_unc,SST_unc,H_unc,W_unc,'[Sv]','Formation [Sv]',...
            dxx,dyy,58,'Fpeak_f_ts','Formation',[-1e-9 1e-9],[0 9e-10],1,month,2,54,SSS,SST,rho_e)
%% Plotting Formation rho
% RHO
        rho_plot(gFrho_all,sigma-1000,tframe,month,n_stat,64,SSS_unc,SST_unc,...
            H_unc,W_unc,'gFrho_all','Formation','[Sv]','Formation [Sv]')
% GEO
        rho_geo(gFrho_all,sigma-1000,ocean,tframe,month,n_stat,59,SSS_unc,SST_unc,...
            H_unc,W_unc,dS,rho,latitude,longitude,lat,lon,dxx,dyy,'Fpeak_f_r',...
            'Formation','[Sv]','Formation [Sv]',1,SSS,SST,rho_e)
end
